### ISSUE TITLE
Add support for numbers of arbitrary precision

### ISSUE THREAD

**Issue by aSemy** [adamko-dev/json5-kotlin#6]
At the moment only Long and Double are supported. This means that numbers are not accurately encoded or decoded.

This limitation is due to a limitation of Kotlinx Serialization https://github.com/Kotlin/kotlinx.serialization/issues/1405 https://github.com/Kotlin/kotlinx.serialization/issues/1051 

The Longs and Doubles could be converted to Java's BigDecimal and BigInteger. Alternatively, and planning for the future a bit more, use a multiplatform Kotlin implementation https://github.com/ionspin/kotlin-multiplatform-bignum.

#### Tasks

- [ ] Decide on an implementation
- [ ] Convert all Longs 
- [ ] Convert all Doubles
